# Generated by Django 5.0.3 on 2024-04-06 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='doctorId',
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 0, 8, 57, 66855, tzinfo=datetime.timezone.utc)),
        ),
    ]
