# Generated by Django 5.0.3 on 2024-04-03 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('doctorId', models.IntegerField()),
                ('createdDate', models.DateTimeField(default=datetime.datetime(2024, 4, 3, 0, 6, 55, 395809, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
