# Generated by Django 5.0.3 on 2024-04-06 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(default='new', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 0, 8, 57, 65965, tzinfo=datetime.timezone.utc)),
        ),
    ]
